### ISSUE TITLE
arbitrary number of states?

### ISSUE THREAD

**Issue by socketwiz** [ColinEberhardt/redux-reducer-array#1]
Thanks for this example and your blog post.  I just had one quick question.  Is it possible to have an arbitrary number of states or are you limited by the number of COUNTER_INITIAL_STATES you create in the INITIAL_STATE array:

https://github.com/ColinEberhardt/redux-reducer-array/blob/master/src/store/reducer.js#L9-L13

**Comment by socketwiz** [comment]
Never mind.  Now that I've downloaded and played with it, I see that you can add as many counters as you like with the addCounterAction action:

https://github.com/ColinEberhardt/redux-reducer-array/blob/master/src/store/reducer.js#L5

It just starts out with 3.  Nice work, thanks again for the example!

**Comment by ColinEberhardt** [comment]
Cool - glad you managed to sort this out :-)
